name: 'Calculate Next Version'
description: 'Calculate next semantic version based on git tags and version type (build, patch, minor, major)'
inputs:
  version_type:
    description: 'Type of version increment (build, patch, minor, major)'
    required: true
    default: 'build'

outputs:
  version:
    description: 'The new version number'
    value: ${{ steps.calculate.outputs.release-version }}
  previous_version:
    description: 'The previous version number'
    value: ${{ steps.calculate.outputs.current-version }}

runs:
  using: "composite"
  steps:
    - name: Checkout with full git history
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Calculate version
      id: calculate
      uses: ./.github/actions/get-version
      with:
        release-type: ${{ inputs.version_type }}

    - name: Display version change
      shell: bash
      run: |
        echo "========================================="
        echo "Version Update"
        echo "========================================="
        echo "Type:     ${{ inputs.version_type }}"
        echo "Previous: ${{ steps.calculate.outputs.current-version }}"
        echo "New:      ${{ steps.calculate.outputs.release-version }}"
        echo "========================================="
