name: 'Deployment Notification'
description: 'Send deployment status notification with consistent formatting'
inputs:
  status:
    description: 'Deployment status (success/failure/warning)'
    required: true
  environment:
    description: 'Environment name (production/staging)'
    required: true
  version:
    description: 'Version number deployed'
    required: false
  version_type:
    description: 'Type of version increment'
    required: false
  url:
    description: 'Deployment URL'
    required: false
  message:
    description: 'Additional message to include'
    required: false
  timestamp:
    description: 'Timestamp of deployment (defaults to current time)'
    required: false

runs:
  using: "composite"
  steps:
    - name: Send notification
      shell: bash
      run: chmod +x ${{ github.action_path }}/entrypoint.swift && ${{ github.action_path }}/entrypoint.swift "${{ inputs.status }}" "${{ inputs.environment }}" "${{ inputs.version }}" "${{ inputs.version_type }}" "${{ inputs.url }}" "${{ inputs.message }}" "${{ inputs.timestamp }}"
