name: 'Run API Tests'
description: 'Execute API integration test suite against application'
inputs:
  base_url:
    description: 'Base URL of the application to test'
    required: true

outputs:
  result:
    description: 'Test result (success/failure)'
    value: ${{ steps.run-tests.outputs.result }}

runs:
  using: "composite"
  steps:
    - name: Run API tests
      id: run-tests
      shell: bash
      env:
        API_BASE_URL: ${{ inputs.base_url }}
      run: chmod +x ${{ github.action_path }}/test-api.swift && ${{ github.action_path }}/test-api.swift
