name: 'Run API Tests'
description: 'Execute API integration test suite against application'
inputs:
  base_url:
    description: 'Base URL of the application to test'
    required: true
  test_script:
    description: 'Path to the test script'
    required: false
    default: 'tests/api/api-tests.sh'

outputs:
  result:
    description: 'Test result (success/failure)'
    value: ${{ steps.run-tests.outputs.result }}
  tests_passed:
    description: 'Number of tests passed'
    value: ${{ steps.run-tests.outputs.passed }}
  tests_failed:
    description: 'Number of tests failed'
    value: ${{ steps.run-tests.outputs.failed }}

runs:
  using: "composite"
  steps:
    - name: Run API tests
      id: run-tests
      shell: bash
      run: chmod +x ${{ github.action_path }}/entrypoint.swift && ${{ github.action_path }}/entrypoint.swift "${{ inputs.base_url }}" "${{ inputs.test_script }}"
