name: 'Run API Tests'
description: 'Execute API integration test suite against application'
inputs:
  base_url:
    description: 'Base URL of the application to test'
    required: true
  test_script:
    description: 'Path to the test script'
    required: false
    default: 'tests/api/api-tests.sh'

outputs:
  result:
    description: 'Test result (success/failure)'
    value: ${{ steps.run-tests.outputs.result }}
  tests_passed:
    description: 'Number of tests passed'
    value: ${{ steps.run-tests.outputs.passed }}
  tests_failed:
    description: 'Number of tests failed'
    value: ${{ steps.run-tests.outputs.failed }}

runs:
  using: "composite"
  steps:
    - name: Run API tests
      id: run-tests
      shell: bash
      run: |
        chmod +x ${{ inputs.test_script }}

        echo "========================================="
        echo "API Integration Tests"
        echo "========================================="
        echo "Target: ${{ inputs.base_url }}"
        echo "Script: ${{ inputs.test_script }}"
        echo ""

        # Run tests and capture output
        if API_BASE_URL="${{ inputs.base_url }}" ${{ inputs.test_script }}; then
          echo "result=success" >> $GITHUB_OUTPUT
          echo ""
          echo "✅ All API tests passed!"
          exit 0
        else
          echo "result=failure" >> $GITHUB_OUTPUT
          echo ""
          echo "❌ API tests failed!"
          exit 1
        fi
