name: 'Extended Monitoring'
description: 'Monitor application health over an extended period with failure tracking'
inputs:
  url:
    description: 'Base URL of the application to monitor'
    required: true
  duration_minutes:
    description: 'Duration to monitor in minutes'
    required: false
    default: '5'
  check_interval_seconds:
    description: 'Interval between health checks in seconds'
    required: false
    default: '30'
  max_consecutive_failures:
    description: 'Maximum consecutive failures before alerting'
    required: false
    default: '3'
  endpoint:
    description: 'Health check endpoint path'
    required: false
    default: '/health'

outputs:
  status:
    description: 'Monitoring status (success/failure)'
    value: ${{ steps.monitor.outputs.status }}
  total_checks:
    description: 'Total number of health checks performed'
    value: ${{ steps.monitor.outputs.total_checks }}
  failures:
    description: 'Number of failed checks'
    value: ${{ steps.monitor.outputs.failures }}

runs:
  using: "composite"
  steps:
    - name: Extended monitoring
      id: monitor
      shell: bash
      run: chmod +x ${{ github.action_path }}/entrypoint.swift && ${{ github.action_path }}/entrypoint.swift "${{ inputs.url }}${{ inputs.endpoint }}" "${{ inputs.duration_minutes }}" "${{ inputs.check_interval_seconds }}" "${{ inputs.max_consecutive_failures }}"
