name: 'Read Version'
description: 'Read version from VERSION file'
inputs:
  version_file:
    description: 'Path to VERSION file'
    required: false
    default: 'VERSION'

outputs:
  version:
    description: 'The version number from VERSION file'
    value: ${{ steps.read.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Read version from file
      id: read
      shell: bash
      run: chmod +x ${{ github.action_path }}/entrypoint.swift && ${{ github.action_path }}/entrypoint.swift "${{ inputs.version_file }}"
