name: 'Setup SwiftLint'
description: 'Install SwiftLint for Linux'
inputs:
  version:
    description: 'SwiftLint version to install'
    required: false
    default: '0.54.0'
  install_path:
    description: 'Installation path for SwiftLint binary'
    required: false
    default: '/usr/local/bin/'

outputs:
  installed_version:
    description: 'SwiftLint version that was installed'
    value: ${{ inputs.version }}

runs:
  using: "composite"
  steps:
    - name: Install SwiftLint
      shell: bash
      run: chmod +x ${{ github.action_path }}/entrypoint.swift && ${{ github.action_path }}/entrypoint.swift "${{ inputs.version }}" "${{ inputs.install_path }}"
