name: 'Increment Version'
description: 'Increment semantic version based on type (build, patch, minor, major)'
inputs:
  version_type:
    description: 'Type of version increment (build, patch, minor, major)'
    required: true
    default: 'build'
  github_token:
    description: 'GitHub token for committing version changes'
    required: true
outputs:
  version:
    description: 'The new version number'
    value: ${{ steps.bump.outputs.version }}
  previous_version:
    description: 'The previous version number'
    value: ${{ steps.get-current.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Get current version
      id: get-current
      shell: bash
      run: |
        CURRENT_VERSION=$(cat VERSION)
        echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
        echo "Current version: $CURRENT_VERSION"

    - name: Increment version
      id: bump
      shell: bash
      run: |
        chmod +x scripts/version-manager.sh

        case "${{ inputs.version_type }}" in
          build)
            NEW_VERSION=$(./scripts/version-manager.sh build)
            ;;
          patch|bugfix)
            NEW_VERSION=$(./scripts/version-manager.sh patch)
            ;;
          minor|feature)
            NEW_VERSION=$(./scripts/version-manager.sh minor)
            ;;
          major|breaking)
            NEW_VERSION=$(./scripts/version-manager.sh major)
            ;;
          *)
            echo "ERROR: Invalid version type: ${{ inputs.version_type }}"
            exit 1
            ;;
        esac

        echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
        echo "Incremented version from ${{ steps.get-current.outputs.version }} to $NEW_VERSION"

    - name: Display version change
      shell: bash
      run: |
        echo "========================================="
        echo "Version Update"
        echo "========================================="
        echo "Type:     ${{ inputs.version_type }}"
        echo "Previous: ${{ steps.get-current.outputs.version }}"
        echo "New:      ${{ steps.bump.outputs.version }}"
        echo "========================================="
