name: 'Git Tag and Push'
description: 'Create a Git tag and push changes to remote repository'
inputs:
  version:
    description: 'Version number for the tag (without v prefix)'
    required: true
  branch:
    description: 'Branch to push'
    required: false
    default: 'main'
  tag_prefix:
    description: 'Prefix for the tag (e.g., "v")'
    required: false
    default: 'v'
  tag_message:
    description: 'Tag message (version will be appended)'
    required: false
    default: 'Release version'
  push_tag:
    description: 'Whether to push the tag'
    required: false
    default: 'true'
  push_branch:
    description: 'Whether to push the branch'
    required: false
    default: 'true'

outputs:
  tag_name:
    description: 'Full tag name created'
    value: ${{ steps.tag.outputs.tag_name }}

runs:
  using: "composite"
  steps:
    - name: Create and push tag
      id: tag
      shell: bash
      run: chmod +x ${{ github.action_path }}/entrypoint.swift && ${{ github.action_path }}/entrypoint.swift "${{ inputs.version }}" "${{ inputs.branch }}" "${{ inputs.tag_prefix }}" "${{ inputs.tag_message }}" "${{ inputs.push_tag }}" "${{ inputs.push_branch }}"
