name: 'Configure Git'
description: 'Configure Git user for GitHub Actions bot'
inputs:
  user_name:
    description: 'Git user name'
    required: false
    default: 'github-actions[bot]'
  user_email:
    description: 'Git user email'
    required: false
    default: 'github-actions[bot]@users.noreply.github.com'

runs:
  using: "composite"
  steps:
    - name: Configure Git
      shell: bash
      run: chmod +x ${{ github.action_path }}/entrypoint.swift && ${{ github.action_path }}/entrypoint.swift "${{ inputs.user_name }}" "${{ inputs.user_email }}"
