name: 'Build and Push Docker Image'
description: 'Build Docker image and push to GitHub Container Registry'
inputs:
  registry:
    description: 'Container registry URL'
    required: true
    default: 'ghcr.io'
  image_name:
    description: 'Docker image name'
    required: true
  version:
    description: 'Version tag for the image'
    required: true
  tags:
    description: 'Additional tags (comma-separated)'
    required: false
    default: ''
  push:
    description: 'Whether to push the image'
    required: false
    default: 'true'
  github_token:
    description: 'GitHub token for registry authentication'
    required: true

outputs:
  image_tag:
    description: 'Full image tag that was built'
    value: ${{ inputs.registry }}/${{ inputs.image_name }}:${{ inputs.version }}
  digest:
    description: 'Image digest'
    value: ${{ steps.build.outputs.digest }}

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.github_token }}

    - name: Generate cache keys
      id: cache-keys
      shell: bash
      run: |
        # Generate hash of Package.resolved for dependency caching
        DEPS_HASH=$(sha256sum todos-fluent/Package.resolved | cut -d' ' -f1 | cut -c1-12)
        echo "deps-hash=${DEPS_HASH}" >> $GITHUB_OUTPUT

        # Generate hash of source files for incremental builds
        SOURCE_HASH=$(find todos-fluent/Sources -type f -name "*.swift" -exec sha256sum {} \; | sort | sha256sum | cut -d' ' -f1 | cut -c1-12)
        echo "source-hash=${SOURCE_HASH}" >> $GITHUB_OUTPUT

        echo "Dependencies hash: ${DEPS_HASH}"
        echo "Source code hash: ${SOURCE_HASH}"

    - name: Prepare tags
      id: prepare-tags
      shell: bash
      run: |
        TAGS="${{ inputs.registry }}/${{ inputs.image_name }}:${{ inputs.version }}"

        # Add additional tags if provided
        if [ -n "${{ inputs.tags }}" ]; then
          IFS=',' read -ra EXTRA_TAGS <<< "${{ inputs.tags }}"
          for tag in "${EXTRA_TAGS[@]}"; do
            tag=$(echo "$tag" | xargs)  # Trim whitespace
            TAGS="$TAGS,${{ inputs.registry }}/${{ inputs.image_name }}:$tag"
          done
        fi

        echo "tags=$TAGS" >> $GITHUB_OUTPUT
        echo "Building with tags: $TAGS"

    - name: Build and push Docker image
      id: build
      uses: docker/build-push-action@v5
      with:
        context: .
        push: ${{ inputs.push }}
        tags: ${{ steps.prepare-tags.outputs.tags }}
        build-args: |
          VERSION=${{ inputs.version }}
        cache-from: |
          type=registry,ref=${{ inputs.registry }}/${{ inputs.image_name }}:builder-cache-${{ steps.cache-keys.outputs.deps-hash }}
          type=registry,ref=${{ inputs.registry }}/${{ inputs.image_name }}:builder-cache-latest
          type=gha
        cache-to: |
          type=registry,ref=${{ inputs.registry }}/${{ inputs.image_name }}:builder-cache-${{ steps.cache-keys.outputs.deps-hash }},mode=max
          type=registry,ref=${{ inputs.registry }}/${{ inputs.image_name }}:builder-cache-latest,mode=max
          type=gha,mode=max
        labels: |
          org.opencontainers.image.version=${{ inputs.version }}
          org.opencontainers.image.created=${{ github.event.repository.updated_at }}
          org.opencontainers.image.revision=${{ github.sha }}

    - name: Display build info
      shell: bash
      run: |
        echo "========================================="
        echo "Docker Build Complete"
        echo "========================================="
        echo "Image: ${{ inputs.registry }}/${{ inputs.image_name }}"
        echo "Version: ${{ inputs.version }}"
        echo "Tags: ${{ steps.prepare-tags.outputs.tags }}"
        echo "Pushed: ${{ inputs.push }}"
        echo "========================================="
