name: 'Build Docker Image'
description: 'Build Docker image with caching'
inputs:
  registry:
    description: 'Container registry URL'
    required: true
    default: 'ghcr.io'
  image_name:
    description: 'Docker image name'
    required: true
  version:
    description: 'Version tag for the image'
    required: true
  tags:
    description: 'Additional tags (comma-separated)'
    required: false
    default: ''
  github_token:
    description: 'GitHub token for registry authentication'
    required: true

outputs:
  image_tag:
    description: 'Full image tag that was built'
    value: ${{ inputs.registry }}/${{ inputs.image_name }}:${{ inputs.version }}
  digest:
    description: 'Image digest'
    value: ${{ steps.build.outputs.digest }}
  tags:
    description: 'All tags that were prepared for the image'
    value: ${{ steps.prepare-tags.outputs.tags }}

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.github_token }}

    - name: Generate cache keys
      id: cache-keys
      shell: bash
      run: chmod +x ${{ github.action_path }}/generate-cache-keys.swift && ${{ github.action_path }}/generate-cache-keys.swift

    - name: Prepare tags
      id: prepare-tags
      shell: bash
      run: chmod +x ${{ github.action_path }}/prepare-tags.swift && ${{ github.action_path }}/prepare-tags.swift "${{ inputs.registry }}" "${{ inputs.image_name }}" "${{ inputs.version }}" "${{ inputs.tags }}"

    - name: Build Docker image
      id: build
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: ${{ steps.prepare-tags.outputs.tags }}
        build-args: |
          VERSION=${{ inputs.version }}
        cache-from: |
          type=registry,ref=${{ inputs.registry }}/${{ inputs.image_name }}:builder-cache-${{ steps.cache-keys.outputs.deps-hash }}
          type=registry,ref=${{ inputs.registry }}/${{ inputs.image_name }}:builder-cache-latest
          type=gha
        cache-to: |
          type=registry,ref=${{ inputs.registry }}/${{ inputs.image_name }}:builder-cache-${{ steps.cache-keys.outputs.deps-hash }},mode=max
          type=registry,ref=${{ inputs.registry }}/${{ inputs.image_name }}:builder-cache-latest,mode=max
          type=gha,mode=max
        labels: |
          org.opencontainers.image.version=${{ inputs.version }}
          org.opencontainers.image.created=${{ github.event.repository.updated_at }}
          org.opencontainers.image.revision=${{ github.sha }}
        outputs: type=docker,dest=/tmp/image.tar

    - name: Display build info
      shell: bash
      run: |
        echo "========================================="
        echo "Docker Build Complete"
        echo "========================================="
        echo "Image: ${{ inputs.registry }}/${{ inputs.image_name }}"
        echo "Version: ${{ inputs.version }}"
        echo "Tags: ${{ steps.prepare-tags.outputs.tags }}"
        echo "Image saved to: /tmp/image.tar"
        echo "========================================="
