name: 'Push Docker Image'
description: 'Push Docker image to GitHub Container Registry'
inputs:
  registry:
    description: 'Container registry URL'
    required: true
    default: 'ghcr.io'
  image_name:
    description: 'Docker image name'
    required: true
  tags:
    description: 'Image tags to push (comma-separated)'
    required: true
  github_token:
    description: 'GitHub token for registry authentication'
    required: true

outputs:
  pushed:
    description: 'Whether the push was successful'
    value: 'true'

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.github_token }}

    - name: Push Docker image
      shell: bash
      run: chmod +x ${{ github.action_path }}/entrypoint.swift && ${{ github.action_path }}/entrypoint.swift "${{ inputs.registry }}" "${{ inputs.image_name }}" "${{ inputs.tags }}"
