name: 'Health Check'
description: 'Perform health check on application endpoint'
inputs:
  url:
    description: 'Base URL of the application'
    required: true
  max_retries:
    description: 'Maximum number of retry attempts'
    required: false
    default: '30'
  retry_interval:
    description: 'Interval between retries in seconds'
    required: false
    default: '2'
  endpoint:
    description: 'Health check endpoint path'
    required: false
    default: '/health'

outputs:
  status:
    description: 'Health check status (success/failure)'
    value: ${{ steps.check.outputs.status }}

runs:
  using: "composite"
  steps:
    - name: Run health check
      id: check
      shell: bash
      run: |
        chmod +x ${{ github.action_path }}/entrypoint.swift
        ${{ github.action_path }}/entrypoint.swift "${{ inputs.url }}" "${{ inputs.endpoint }}" "${{ inputs.max_retries }}" "${{ inputs.retry_interval }}"
