name: 'Health Check'
description: 'Perform health check and version verification on application endpoint'
inputs:
  url:
    description: 'Base URL of the application'
    required: true
  max_retries:
    description: 'Maximum number of retry attempts'
    required: false
    default: '30'
  retry_interval:
    description: 'Interval between retries in seconds'
    required: false
    default: '2'
  endpoint:
    description: 'Health check endpoint path'
    required: false
    default: '/health'
  expected_version:
    description: 'Expected version string'
    required: false
    default: ''
  expected_build_number:
    description: 'Expected build number'
    required: false
    default: ''
  expected_environment:
    description: 'Expected environment name'
    required: false
    default: ''

outputs:
  status:
    description: 'Health check status (success/failure)'
    value: ${{ steps.check.outputs.status }}

runs:
  using: "composite"
  steps:
    - name: Run health check
      id: check
      shell: bash
      run: |
        chmod +x ${{ github.action_path }}/entrypoint.swift
        ${{ github.action_path }}/entrypoint.swift "${{ inputs.url }}" "${{ inputs.endpoint }}" "${{ inputs.max_retries }}" "${{ inputs.retry_interval }}" "${{ inputs.expected_version }}" "${{ inputs.expected_build_number }}" "${{ inputs.expected_environment }}"
