source "https://rubygems.org"

gem "jekyll", "~> 3.9.0"
gem "just-the-docs", "0.7.0"

# Plugins
group :jekyll_plugins do
  gem "jekyll-seo-tag", "~> 2.8"
  gem "jekyll-github-metadata", ">= 2.15"
  gem "jekyll-include-cache", "~> 0.2.1"
end

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]
