name: "Set App Version"
description: "Update the hardcoded version in the application code"

inputs:
  version:
    description: "Version to set in the app code"
    required: true
  environment:
    description: "Environment (staging or production)"
    required: true
    default: "staging"

runs:
  using: "composite"
  steps:
    - name: Set version in app code
      shell: bash
      run: chmod +x ${{ github.action_path }}/entrypoint.swift && ${{ github.action_path }}/entrypoint.swift "${{ inputs.version }}" "${{ inputs.environment }}"
