name: "Docker Cleanup"
description: "Clean up old Docker containers and images via SSH"
inputs:
  ssh_host:
    description: "SSH host"
    required: true
  ssh_user:
    description: "SSH user"
    required: true
  ssh_key:
    description: "SSH private key"
    required: true
  # ssh_key_passphrase:
  #   description: "SSH private key passphrase"
  #   required: false
  ssh_port:
    description: "SSH port"
    required: false
    default: "22"
  container_name:
    description: "Container name to remove (with -previous suffix)"
    required: true
  prune_images:
    description: "Whether to prune unused images"
    required: false
    default: "true"
  deploy_path:
    description: "Deployment directory on server"
    required: false
    default: "/opt/todos-app"

runs:
  using: "composite"
  steps:
    - name: Upload server-manager.swift to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ inputs.ssh_host }}
        username: ${{ inputs.ssh_user }}
        key: ${{ inputs.ssh_key }}
        port: ${{ inputs.ssh_port }}
        source: ".github/remote-scripts/server-manager.swift"
        target: "~/"
        strip_components: 2

    - name: Remove old container and prune images
      uses: appleboy/ssh-action@v1.2.4
      env:
        CONTAINER_NAME: ${{ inputs.container_name }}
        PRUNE_IMAGES: ${{ inputs.prune_images }}
        DEPLOY_PATH: ${{ inputs.deploy_path }}
      with:
        host: ${{ inputs.ssh_host }}
        username: ${{ inputs.ssh_user }}
        key: ${{ inputs.ssh_key }}
        port: ${{ inputs.ssh_port }}
        envs: CONTAINER_NAME,PRUNE_IMAGES,DEPLOY_PATH
        script: |
          # Source Swiftly environment
          source ~/.local/share/swiftly/env.sh

          # Make script executable
          chmod +x ~/server-manager.swift

          # Run cleanup
          ~/server-manager.swift cleanup
